### ISSUE TITLE
POST data to Web

### ISSUE THREAD

**Issue by Alehap** [phil-brown/droidQuery#11]
Please help me to post data to web.
I cannot configure data for posting.

.data(????????) <~~ can you example something for me, thanks too much

$.ajax(new AjaxOptions().url("http://www.example.com")
                        .type("post")
                        .dataType("text")
                        .data(????????)
                        .context(this)
                        .success(new Function() {
                            @Override
                            public void invoke($ droidQuery, Object... params) {
                                JSONObject json = (JSONObject) params[0];
                                //handle json response. Also see $.map(JSONObject) for parsing
                            }
                        })
                        .error(new Function() {
                            @Override
                            public void invoke($ droidQuery, Object... params) {
                                AjaxError e = (AjaxError) params[0];
                                Log.e("$", "Error: " + e.status + ": " + e.error);
                            }
                        }));

**Comment by nikolai94** [comment]
Hey i had the same problem i just need to set .contentType("application/json"), then it worked fine :)
