### ISSUE TITLE
POST Data with DroidQuery

### ISSUE THREAD

**Issue by ClementDelaunay** [phil-brown/droidQuery#15]
Hello, I am trying to send data to my API, but without success.

In my code below, I get the form data in a JSON and I pass them in the request with the toString method.
I also tried with the object or putting data directly in the function.

The request runs correctly but without the data. I get an API response telling me the fields are empty. Also, on my server logs, I receive a POST data but also empty.
I tried with the dataType "text", but nothing happens, I don't understand.

Thank you in advance for your support!

```java
private OnClickListener clickListenerConnect = new View.OnClickListener() {
        @Override
        public void onClick(View v) {

            String password = textPassword.getText().toString();
            String mail = textMail.getText().toString();

            JSONObject dataPost = new JSONObject();
            try {
                dataPost.put("password", password);
                dataPost.put("mail", mail);
            } catch (JSONException e) {
                e.printStackTrace();
            }

            $.ajax(new AjaxOptions()
                    .url("http://example.com/login")
                    .type("POST")
                    .data(dataPost.toString())
                    .dataType("json")
                    .success(new Function() {
                        @Override
                        public void invoke($ droidQuery, Object... params) {
                            JSONObject response = (JSONObject) params[0];
                            Log.e("AjaxSuccess", response.toString());
                        }
                    })
                    .error(new Function() {
                        @Override
                        public void invoke($ droidQuery, Object... params) {
                            if (pDialog.isShowing())
                                pDialog.dismiss();

                            int statusCode = (Integer) params[1];
                            String error = (String) params[2];
                            Log.e("AjaxError", statusCode + " " + error);
                        }
                    }));

        }
    };
```

**Comment by phil-brown** [comment]
Hmm... that looks right. What logs do you see if you add the *debug* option?

    new AjaxOptions().debug()...

**Comment by ClementDelaunay** [comment]
Thank you for your answer, but I can't add the debug option, it kills the rest of the query...

![capture d ecran 2015-03-27 a 10 39 27](https://cloud.githubusercontent.com/assets/5664370/6865442/174033b0-d46e-11e4-8345-cd2f2b9c17a1.png)

With this error in the console : 

![capture d ecran 2015-03-27 a 10 42 36](https://cloud.githubusercontent.com/assets/5664370/6865452/32484a3a-d46e-11e4-83da-d1a231d4899b.png)

**Comment by ClementDelaunay** [comment]
I added the true argument to the debug option, but I have no difference in the logs, even in verbose mode...

**Comment by phil-brown** [comment]
@ClementDelaunay yes, I meant the `.debug(true)` option. This should show additional logs with the tag *Ajax*. Also, what version of *droidQuery* are you using?
