### ISSUE TITLE
Can this be used with android studio? The how to include instructions seem to only apply to eclipse

### ISSUE THREAD

**Issue by alexf1** [phil-brown/droidQuery#18]

**Comment by phil-brown** [comment]
@alexf1 Currently, you need to place the jar into your `libs` directory in your project or module (create if you don't have it), then this line in your gradle dependencies will automatically include the code into your project:

``` groovy
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
}
```

**Comment by alexf1** [comment]
When I try to build the jar with ant it fails. Is there a way to download it directly?
@alexf1 Currently, you need to place the jar into your `libs` directory in your project or module (create if you don't have it), then this line in your gradle dependencies will automatically include the code into your project:

``` groovy
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
}
```

---

**Comment by phil-brown** [comment]
It looks like I'll have to generate a new jar for the latest updates, however you can get find a recent version at https://github.com/phil-brown/droidQuery/releases/tag/1.1.0

**Comment by phil-brown** [comment]
@alexf1 if you use the old Ajax API, you'll also need to add this under the `android` section of build.gradle:

```
useLibrary 'org.apache.http.legacy'
```

You can also opt to use the new API using AjaxOptions, which changes Ajax calls to using HttpUrlConnection instead:

```
new AjaxOptions().useNewApi();
```

**Comment by alexf1** [comment]
So if I use the new one is it then comparable with sdk23? There was something that was deprecated in the newest SDK, I just can't recall what it was.
@alexf1 if you use the old Ajax API, you'll also need to add this under the `android` section of build.gradle:

    useLibrary 'org.apache.http.legacy'

You can also opt to use the new API using AjaxOptions, which changes Ajax calls to using HttpUrlConnection instead:

    new AjaxOptions().useNewApi();

---

**Comment by alexf1** [comment]
When I try to build it I get “BUILD FAILED” Target “help” does not exist in the project. Thanks for getting back to me by the way

**Comment by alexf1** [comment]
Deleted some stupid questions. I'll create a new sdk23 project and use the jar from the link you gave and see if I have any issues. Could be the issues I had were from my method of including the library in my project. Thanks Phil, this library is a god send.

**Comment by alexf1** [comment]
@phil-brown Hey Phil, 

Sorry to bug you again, once I get my first ajax call working I'm sure the rest will be smooth sailing. I'm getting the following. I followed all your directions and it all seemed to have worked until I try to execute a task.

public void getSession(View view) {

```
    EditText txtLogin = (EditText)findViewById(R.id.txtLogin);
    EditText txtPassword = (EditText)findViewById(R.id.txtPassword);
    String globalKey = "key";

    $.ajax(new AjaxOptions().url("https://portal.bomimed.com:62251/CRMService.svc/Login")
            .type("POST")
            .data("{\"userid\":\"" + txtLogin.getText().toString() + "\",\"password\":\"" + txtPassword.getText().toString() + "\",\"gkey\":\"" + globalKey + "\"}")
            .dataType("Json")
            .context(this).success(new Function() {
                @Override
                public void invoke($ droidQuery, Object... params) {
                    //ScriptResponse response = (ScriptResponse) params[0];
                    //droidQuery.alert(response.output);
                    Log.e("$", "Worked");
                }
            }).error(new Function() {
                @Override
                public void invoke($ droidQuery, Object... params) {
                    Log.e("$", "broke");
                }
            }));
}
```

03-07 10:39:41.938 1718-1760/com.example.mferreira.crm I/OpenGLRenderer: Initialized EGL, version 1.4
03-07 10:41:24.617 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.css.CSSSelector>
03-07 10:41:24.618 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.css.CSSSelector>
03-07 10:41:24.619 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.css.CSSSelector>
03-07 10:41:24.621 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 10:41:24.622 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 10:41:24.622 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 10:41:24.622 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 10:41:24.623 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 10:41:24.636 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$6>
03-07 10:41:24.636 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$6>
03-07 10:41:24.637 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$7>
03-07 10:41:24.637 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$7>
03-07 10:41:24.657 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$12>
03-07 10:41:24.657 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$12>
03-07 10:41:24.659 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$18>
03-07 10:41:24.659 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$18>
03-07 10:41:24.662 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$16>
03-07 10:41:24.662 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$16>
03-07 10:41:24.663 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$14>
03-07 10:41:24.663 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$14>
03-07 10:41:24.667 1718-1718/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 10:41:24.668 1718-1718/com.example.mferreira.crm E/droidQuery: Could not complete ajax task!
                                                                     java.lang.NoClassDefFoundError: self.philbrown.droidQuery.AjaxTask
                                                                         at self.philbrown.droidQuery.$.ajax($.java:4490)
                                                                         at com.example.mferreira.crm.LoginActivity.getSession(LoginActivity.java:77)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                         at android.view.View.performClick(View.java:5204)
                                                                         at android.view.View$PerformClick.run(View.java:21153)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Again sorry to bug you, there isn't really any other resources to look into it with. Thanks Phil.

**Comment by alexf1** [comment]
@phil-brown Hey Phil, Got it down to this by including the .jars droidquery needs. I just don't know what's missing now or if it's an issue with the droidquery jar

03-07 12:06:02.535 6493-6517/com.example.mferreira.crm I/OpenGLRenderer: Initialized EGL, version 1.4
03-07 12:06:10.897 6493-6493/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 12:06:10.897 6493-6493/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 12:06:10.898 6493-6493/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 12:06:10.898 6493-6493/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 12:06:10.898 6493-6493/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 12:06:10.932 6493-6493/com.example.mferreira.crm I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
03-07 12:06:10.933 6493-6493/com.example.mferreira.crm E/droidQuery: Could not complete ajax task!
java.lang.NoClassDefFoundError: self.philbrown.droidQuery.AjaxTask
                                                                         at self.philbrown.droidQuery.$.ajax($.java:4490)

**Comment by alexf1** [comment]
Fixed it...No idea how.
