### ISSUE TITLE
GZIPped JSON data

### ISSUE THREAD

**Issue by mrsean2k** [phil-brown/droidQuery#8]
Is there a way to detect if a returned JSON stream has been gzipped as a result of a $.ajax call?

In my existing code, I check the response headers to see if gzip is indicated, then run it through standard GZIPInputStream to get to the uncompressed string, and so the JSONObject.

Using $.ajax I couldn't see how I could check to see if it was GZIPped in .success, or how to cast / process params[0] afterwards.

**Comment by phil-brown** [comment]
@mrsean2k the [latest update](https://github.com/phil-brown/droidQuery/commit/bbd66fabbfe5f50c84c9f4843c0deb10dc5242b6) now automatically handles *gzip* compression, so you no longer have to process the data yourself using the *raw* dataType.
